# braincell_agent.py
# Run from: C:\Leonid\GitHub\XiaolanWu\BrainCell
# Requires: pip install anthropic
# Requires: braincell_map.json (generated by braincell_mapper.py)
#
# Usage:
#   ask  <question>          — ask the agent about any file or concept
#   search <query>           — find relevant files by keyword
#   modify <file> <task>     — propose a modification (requires your approval)
#   explain <file>           — full biophysical explanation of a MOD/HOC/PY file
#   exit                     — quit

import sys
import os
import json
from pathlib import Path

# ── Auto-add common Anaconda user-package paths so 'anthropic' is found ──────
for _candidate in [
    Path.home() / "AppData" / "Roaming" / "Python" / "Python311" / "site-packages",
    Path.home() / "AppData" / "Roaming" / "Python" / "Python312" / "site-packages",
    Path.home() / "anaconda3" / "Lib" / "site-packages",
]:
    if _candidate.exists() and str(_candidate) not in sys.path:
        sys.path.insert(0, str(_candidate))

import anthropic

# ── Configuration ──────────────────────────────────────────────────────────────

# Auto-detect repo root: the folder this script lives in
REPO = Path(__file__).resolve().parent

# Set your API key here, or use:  setx ANTHROPIC_API_KEY "sk-ant-..." (run once in Anaconda Prompt)
# os.environ["ANTHROPIC_API_KEY"] = "sk-ant-YOUR_KEY_HERE"

CLIENT = anthropic.Anthropic()   # reads ANTHROPIC_API_KEY from environment

MODEL = "claude-opus-4-6"        # best for scientific code; swap for claude-sonnet-4-6 to save cost

# ── Load repository map ────────────────────────────────────────────────────────

MAP_PATH = REPO / "braincell_map.json"
if not MAP_PATH.exists():
    raise FileNotFoundError(
        "braincell_map.json not found.\n"
        "Run braincell_mapper.py first to generate the repository index."
    )

with open(MAP_PATH, encoding="utf-8") as f:
    REPO_MAP = json.load(f)

# ── System prompt ──────────────────────────────────────────────────────────────

SYSTEM = """You are an expert in computational neurobiology and the NEURON simulator.
You are working with BrainCell — a platform developed by the Savtchenko/Rusakov Lab (UCL)
for simulating neurons and astrocytes with nano-scale geometry precision.

REPOSITORY STRUCTURE:
  _Code/
    Managers/       — BioManager, SynManager, GapJuncManager, InhomManager, StochManager, ExportManager
    Export/         — simulation data export
    Extracellular/  — extracellular ion diffusion
    Simulations/    — ready-to-run simulations (SimMyelinatedAxon, etc.)
    InterModular/   — cross-module utilities and GUI wrappers
    Import/         — cell morphology import (.swc, .asc, .hoc)
    NanoSeeding/    — nanoscopic spine/process generation
    NanoCore/       — nano-geometry calculation core
  Mechanisms/
    Astrocyte/MOD_files/   — gapCa*, GAT1_Bicho, Kir, kdrglia
    Neuron/MOD_files/      — AMPASyn, GABA_tonic, Na/K channels, nkpump
    Common/MOD_files/      — cadifus, GluTrans, FRAP, gap*, diffusion helpers
  Biophysics/      — JSON simulation configs (Astrocyte/ and Neuron/)
  Geometry/        — cell morphologies (.hoc)
  Nanogeometry/    — morphologies with generated nano-structures
  External simulations/ — standalone reference models (boosting, modeldb_ventralAD)

KEY MOD FILES:
  GluTrans.mod      — astrocytic glutamate transporter (ions: glu, na, k)
  gapCa.mod         — calcium gap junctions (astrocyte)
  AMPASyn.mod       — AMPA synapse (point process)
  cadifus.mod       — Ca2+ / IP3 diffusion (KINETIC scheme)
  Kir4.mod          — Kir4.1 inward-rectifier K+ channel (astrocyte)
  GAT1_Bicho.mod    — GABA transporter (KINETIC scheme)
  nkpump.mod        — Na/K-ATPase pump (ions: k, na)
  _InsideOutDiffHelper.mod  — intracellular diffusion (all ions)
  _OutsideInDiffHelper.mod  — extracellular diffusion (all ions)

RESPONSE STYLE:
  - Always reference the specific file and line number when suggesting changes.
  - For MOD modifications: verify USEION declarations, RANGE variables, and units (mA/cm2, mM, ms).
  - Show a diff rather than the full file when changes are small.
  - Explain the underlying biophysics, not just the code.
"""

# ── Helper functions ───────────────────────────────────────────────────────────

def search(query: str) -> list[str]:
    """Return up to 8 file paths most relevant to the query."""
    q = query.lower()
    results = []

    for m in REPO_MAP["mod"]:
        score = sum([
            q in m["file"].lower(),
            q in m["title"].lower(),
            q in m["suffix"].lower(),
            any(q in ion for ion in m["ions"]),
            q in m["point_process"].lower(),
        ])
        if score:
            results.append((score, m["file"]))

    for h in REPO_MAP["hoc"]:
        if q in h["file"].lower():
            results.append((1, h["file"]))

    for p in REPO_MAP["py"]:
        if q in p["file"].lower():
            results.append((1, p["file"]))

    # Deduplicate and sort by score
    seen = set()
    unique = []
    for score, path in sorted(results, reverse=True):
        if path not in seen:
            seen.add(path)
            unique.append(path)
    return unique[:8]


def read_file(filepath: str, max_chars: int = 12_000) -> str:
    """Read a file from the repository, truncating if necessary."""
    try:
        content = (REPO / filepath).read_text(encoding="utf-8", errors="ignore")
        if len(content) > max_chars:
            return content[:max_chars] + f"\n\n... [file truncated at {max_chars} chars]"
        return content
    except Exception as e:
        return f"[Could not read {filepath}: {e}]"


def build_context(files: list[str]) -> str:
    """Build a context string from a list of file paths."""
    n_mod = len(REPO_MAP["mod"])
    n_hoc = len(REPO_MAP["hoc"])
    n_py  = len(REPO_MAP["py"])
    ctx = f"Repository: {n_mod} MOD, {n_hoc} HOC, {n_py} Python files.\n\n"

    for filepath in files:
        ctx += f"\n{'='*60}\nFILE: {filepath}\n{'='*60}\n"
        ctx += read_file(filepath)
        ctx += "\n"

    return ctx


# ── Core agent functions ───────────────────────────────────────────────────────

def ask(question: str, files: list[str] | None = None) -> str:
    """Ask the agent a question. Auto-searches for relevant files if none provided."""
    if files is None:
        files = search(question)

    context = build_context(files)

    response = CLIENT.messages.create(
        model=MODEL,
        max_tokens=4096,
        system=SYSTEM,
        messages=[{
            "role": "user",
            "content": f"{context}\n\nQuestion: {question}"
        }]
    )
    return response.content[0].text


def explain(filepath: str) -> str:
    """Ask the agent for a full explanation of a single file."""
    content = read_file(filepath)
    response = CLIENT.messages.create(
        model=MODEL,
        max_tokens=4096,
        system=SYSTEM,
        messages=[{
            "role": "user",
            "content": (
                f"FILE: {filepath}\n\n{content}\n\n"
                "Please provide a comprehensive explanation of this file:\n"
                "1. What biological/biophysical process does it model?\n"
                "2. What are the key parameters and their physiological meaning?\n"
                "3. What are the state variables and their dynamics?\n"
                "4. How does it interact with other mechanisms in BrainCell?\n"
                "5. Are there any known limitations or potential improvements?"
            )
        }]
    )
    return response.content[0].text


def modify(filepath: str, instruction: str) -> None:
    """
    Ask the agent to modify a file.
    The proposed change is shown for your review before anything is saved.
    """
    content = read_file(filepath)

    response = CLIENT.messages.create(
        model=MODEL,
        max_tokens=8192,
        system=SYSTEM,
        messages=[{
            "role": "user",
            "content": (
                f"FILE: {filepath}\n\n{content}\n\n"
                f"Task: {instruction}\n\n"
                "Return ONLY the complete modified file content, no explanations outside the code. "
                "Add any necessary comments inside the code itself."
            )
        }]
    )

    new_content = response.content[0].text

    print(f"\n{'='*60}")
    print(f"PROPOSED CHANGES TO: {filepath}")
    print(f"{'='*60}")
    preview = new_content if len(new_content) <= 3000 else new_content[:3000] + "\n... [preview truncated]"
    print(preview)
    print(f"{'='*60}")

    answer = input("\nSave changes? (y/n): ").strip().lower()
    if answer == "y":
        out_path = REPO / filepath
        out_path.write_text(new_content, encoding="utf-8")
        print(f"Saved: {out_path}")
    else:
        print("Cancelled — no changes written.")


# ── Interactive CLI ────────────────────────────────────────────────────────────

HELP_TEXT = """
Commands:
  ask <question>             Ask anything about the codebase
  search <keyword>           Find relevant files
  explain <relative/path>    Full explanation of a file
  modify <relative/path> <task>   Propose a modification (you approve before saving)
  help                       Show this message
  exit                       Quit

Examples:
  ask How does the GluTrans mechanism work?
  ask What files handle extracellular K+ diffusion?
  search calcium
  explain Mechanisms/Common/MOD_files/GluTrans.mod
  modify Mechanisms/Astrocyte/MOD_files/Kir4.mod  Add Q10 temperature dependence (Q10=2.2)
"""


def main():
    print("=" * 60)
    print("  BrainCell AI Agent")
    print("  Repository:", REPO)
    print(f"  Index: {len(REPO_MAP['mod'])} MOD  {len(REPO_MAP['hoc'])} HOC  {len(REPO_MAP['py'])} PY")
    print("=" * 60)
    print('Type "help" for available commands, "exit" to quit.\n')

    while True:
        try:
            raw = input("> ").strip()
        except (EOFError, KeyboardInterrupt):
            print("\nGoodbye.")
            break

        if not raw:
            continue

        cmd_parts = raw.split(" ", 1)
        cmd = cmd_parts[0].lower()
        rest = cmd_parts[1] if len(cmd_parts) > 1 else ""

        if cmd in ("exit", "quit"):
            print("Goodbye.")
            break

        elif cmd == "help":
            print(HELP_TEXT)

        elif cmd == "search":
            if not rest:
                print("Usage: search <keyword>")
                continue
            results = search(rest)
            if results:
                print(f"Found {len(results)} relevant file(s):")
                for r in results:
                    print(f"  {r}")
            else:
                print("No matching files found.")

        elif cmd == "explain":
            if not rest:
                print("Usage: explain <relative/path/to/file>")
                continue
            print("\nAnalysing...\n")
            print(explain(rest))

        elif cmd == "modify":
            # Format: modify <filepath> <instruction>
            parts = rest.split(" ", 1)
            if len(parts) < 2:
                print("Usage: modify <relative/path/to/file> <instruction>")
                continue
            filepath, instruction = parts[0], parts[1]
            modify(filepath, instruction)

        elif cmd == "ask":
            question = rest if rest else raw   # allow bare questions without "ask" prefix
            print("\nThinking...\n")
            print(ask(question))

        else:
            # No command prefix — treat the whole line as a question
            print("\nThinking...\n")
            print(ask(raw))


if __name__ == "__main__":
    main()
